/*              Drop Tables             */

DROP TABLE INVOICE;
DROP TABLE REVIEW;
DROP TABLE ORDERITEM;
DROP TABLE CART;
DROP TABLE ORDERS;
DROP TABLE ARTWORK;
DROP TABLE SUPPLIER;
DROP TABLE MEMBER;
DROP TABLE CURATOR;
DROP TABLE ARTIST;
